INSERT INTO project_attachments (project_type, project_id, name, file_url) VALUES
('binui', 51, 'תרשים מיקום כללי', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p0_1.jpg'),
('binui', 51, 'תוכנית מרתף', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p1_1.png'),
('binui', 51, 'תוכנית קומת קרקע', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p1_2.png'),
('binui', 51, 'תוכנית גג', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p2_1.png'),
('binui', 51, 'חתך העמדה א', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p2_2.png'),
('binui', 51, 'חתך העמדה ב', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p2_3.png'),
('binui', 51, 'חתך מפלסים', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p3_1.png'),
('binui', 51, 'תנועת הולכי רגל', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p3_2.png'),
('binui', 51, 'תוכנית שטחים', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p4_1.png'),
('binui', 51, 'טבלת שטחים', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p4_2.png'),
('binui', 51, 'חתך גובה בניין', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p4_3.png'),
('binui', 51, 'טבלת נתוני מגרש', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p5_1.png'),
('binui', 51, 'הדמיית חזית א', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p5_2.jpg'),
('binui', 51, 'הדמיית חזית ב', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p5_3.jpg'),
('binui', 51, 'תרשים תכנון עתידי', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p6_1.png'),
('binui', 51, 'תרשים מתחמים', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p6_2.png'),
('binui', 51, 'חתך מגורים - מגרש 51', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p8_1.png'),
('binui', 51, 'חתך מלון - מגרש 46', 'https://brvjdkvhhmiefwssjryc.supabase.co/storage/v1/object/public/project-files/binui/51/img_p10_1.png');